[build]
functions = "functions" # Directory for your lambda functions
command = "npm run build" # Build command
publish = "public" # Publish directory for static files

[[redirects]]
  from = "/*"
  to = "https://tasky-manager-api.netlify.app/:splat"
  status = 200