[build]
  functions = "functions"
  command = "npm run build" 
  publish = "/"

[[redirects]]
  from = "/*"
  to = "https://tasky-manager-api.netlify.app/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"